; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = "drupal"
; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[startik][download][type] = ""
;projects[startik][download][url] = ""
;projects[startik][type] = "module"

; Core functionality
projects[ctools][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[views_accordion][subdir] = "contrib"
projects[views_autocomplete_filters][subdir] = "contrib"
projects[views_data_export][subdir] = "contrib"
projects[views_slideshow][subdir] = "contrib"
projects[entity][subdir] = "contrib"
projects[entityreference][subdir] = "contrib"


; Administration
projects[admin_menu][subdir] = "contrib/#DEVELOPER"
;   projects[book_helper][subdir] = "contrib"
;projects[ccl][subdir] = "contrib"
;projects[entityreference_prepopulate][subdir] = "contrib"


; Development
projects[backup_migrate][subdir] = "contrib/#DEVELOPER"
projects[devel][subdir] = "contrib/#DEVELOPER"
;projects[crazyegg][subdir] = "contrib"
;projects[spaces][subdir] = "contrib"


projects[auto_nodetitle][subdir] = "contrib"

; Presentation
;   projects[block_class][subdir] = "contrib"
projects[fences][subdir] = "contrib"
projects[context][subdir] = "contrib"
;   projects[context_condition_theme][subdir] = "contrib"
;   projects[context_entity_field][subdir] = "contrib"
projects[ds][subdir] = "contrib"
;   projects[exclude_node_title][subdir] = "contrib"




; Search

;projects[facetapi][subdir] = "contrib"
;projects[facetapi_pretty_paths][subdir] = "contrib"










projects[features][subdir] = "contrib"

;   projects[feeds][subdir] = "contrib"
;projects[feeds_tamper][subdir] = "contrib"
;projects[feeds_tamper_php][subdir] = "contrib"
;projects[feeds_xpathparser][subdir] = "contrib"



projects[field_group][subdir] = "contrib"

projects[field_permissions][subdir] = "contrib"

projects[media][subdir] = "contrib"

projects[globalredirect][subdir] = "contrib"

projects[google_analytics][subdir] = "contrib"

projects[honeypot][subdir] = "contrib"

projects[htmlpurifier][subdir] = "contrib"

projects[insert_view][subdir] = "contrib"

projects[job_scheduler][subdir] = "contrib"

projects[libraries][subdir] = "contrib"

projects[linkit][subdir] = "contrib"

projects[login_destination][subdir] = "contrib"

projects[media_vimeo][subdir] = "contrib"

projects[media_youtube][subdir] = "contrib"



projects[menu_block][subdir] = "contrib"

projects[metatag][subdir] = "contrib"

projects[module_filter][subdir] = "contrib"

projects[name][subdir] = "contrib"

projects[oauth][subdir] = "contrib"

projects[] = "pathauto"
projects[pathologic][subdir] = "contrib"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[plus_blocks_views][download][type] = ""
projects[plus_blocks_views][download][url] = ""
projects[plus_blocks_views][type] = "module"
projects[plus_blocks_views][subdir] = "custom/fx_modules/plus_blocks"

projects[publishcontent][subdir] = "contrib"

projects[services][subdir] = "contrib"

projects[rules][subdir] = "contrib"

projects[save_edit][subdir] = "contrib"

projects[scheduler][subdir] = "contrib"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[search_apex_feed][download][type] = ""
projects[search_apex_feed][download][url] = ""
projects[search_apex_feed][type] = "module"
projects[search_apex_feed][subdir] = "custom/search_apex/client"

projects[search_api][subdir] = "contrib"

projects[search_api_db][subdir] = "contrib"

projects[services_ipauth][subdir] = "contrib"

projects[services_views][subdir] = "contrib"

projects[stringoverrides][subdir] = "contrib"

projects[strongarm][subdir] = "contrib"

projects[taxonomy_access_fix][subdir] = "contrib"

projects[taxonomy_display][subdir] = "contrib"

projects[taxonomy_menu][subdir] = "contrib"

projects[term_reference_tree][subdir] = "contrib"

projects[token][subdir] = "contrib"

projects[twitter][subdir] = "contrib"

projects[user_picture_field][subdir] = "contrib"

projects[view_unpublished][subdir] = "contrib"

projects[viewfield][subdir] = "contrib"



projects[webform][subdir] = "contrib"

projects[workbench][subdir] = "contrib"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.x"

projects[xmlsitemap][subdir] = "contrib"

; Themes
projects[] = "sasson"
projects[] = "omega"
projects[] = "antonelli"
projects[] = "basic"
projects[] = "beta"
projects[bootstrap][subdir] = "contrib"

projects[mothership][subdir] = "contrib/mothership"

projects[] = "navin"
projects[] = "omega_kickstart"
projects[] = "respond"
projects[] = "rubik"
projects[stanley][subdir] = "contrib"

projects[] = "stark"
projects[] = "tao"
projects[] = "zen"
; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[apply_filter][download][type] = ""
projects[apply_filter][download][url] = ""
projects[apply_filter][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ckeditor_config][download][type] = ""
projects[ckeditor_config][download][url] = ""
projects[ckeditor_config][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[contextual_nodelinks][download][type] = ""
projects[contextual_nodelinks][download][url] = ""
projects[contextual_nodelinks][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deduplicate_nodes][download][type] = ""
projects[deduplicate_nodes][download][url] = ""
projects[deduplicate_nodes][type] = "module"

projects[eu-cookie-compliance][type] = "module"
projects[eu-cookie-compliance][download][type] = "git"
projects[eu-cookie-compliance][download][url] = "http://git.drupal.org/project/eu-cookie-compliance.git"
projects[eu-cookie-compliance][download][branch] = "7.x-2.x"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[fx_glue][download][type] = ""
projects[fx_glue][download][url] = ""
projects[fx_glue][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[fx_replace][download][type] = ""
projects[fx_replace][download][url] = ""
projects[fx_replace][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[institution_context][download][type] = ""
projects[institution_context][download][url] = ""
projects[institution_context][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[jquery_update][download][type] = ""
projects[jquery_update][download][url] = ""
projects[jquery_update][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[lexicon_define][download][type] = ""
projects[lexicon_define][download][url] = ""
projects[lexicon_define][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[link][download][type] = ""
projects[link][download][url] = ""
projects[link][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[oldsite_redirect][download][type] = ""
projects[oldsite_redirect][download][url] = ""
projects[oldsite_redirect][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[plus_blocks][download][type] = ""
projects[plus_blocks][download][url] = ""
projects[plus_blocks][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[plus_search][download][type] = ""
projects[plus_search][download][url] = ""
projects[plus_search][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[plus_search_simple][download][type] = ""
projects[plus_search_simple][download][url] = ""
projects[plus_search_simple][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[plus_search_simple2][download][type] = ""
projects[plus_search_simple2][download][url] = ""
projects[plus_search_simple2][type] = "module"

projects[search_apex][type] = "module"
projects[search_apex][download][type] = "git"
projects[search_apex][download][url] = "git@github.com:tombola/search_apex.git"

projects[userlike][type] = "module"
projects[userlike][download][type] = "git"
projects[userlike][download][url] = "http://git.drupal.org/sandbox/zakx/1558786.git"
projects[userlike][download][branch] = "7.x-1.x"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[webform_dynamic_recipients][download][type] = ""
projects[webform_dynamic_recipients][download][url] = ""
projects[webform_dynamic_recipients][type] = "module"

; Themes
;projects[fx_themes][type] = "theme"
;projects[fx_themes][download][type] = "git"
;projects[fx_themes][download][url] = "git@github.com:tombola/fx_themes.git"
;projects[fx_themes][download][branch] = "hologram"
projects[] = "stark"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[open_framework][download][type] = ""
;projects[open_framework][download][url] = ""
;projects[open_framework][type] = "theme"

;projects[strapping][type] = "theme"
;projects[strapping][download][type] = "git"
;projects[strapping][download][url] = "git@github.com:tombola/strapping.git"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;libraries[bootstrap][download][type] = ""
;libraries[bootstrap][download][url] = ""
;libraries[bootstrap][directory_name] = "bootstrap"
;libraries[bootstrap][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[fullcalendar][download][type] = ""
libraries[fullcalendar][download][url] = ""
libraries[fullcalendar][directory_name] = "fullcalendar"
libraries[fullcalendar][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[GoogleNexusWebsiteMenu][download][type] = ""
libraries[GoogleNexusWebsiteMenu][download][url] = ""
libraries[GoogleNexusWebsiteMenu][directory_name] = "GoogleNexusWebsiteMenu"
libraries[GoogleNexusWebsiteMenu][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[htmlpurifier][download][type] = ""
libraries[htmlpurifier][download][url] = ""
libraries[htmlpurifier][directory_name] = "htmlpurifier"
libraries[htmlpurifier][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[iCalcreator][download][type] = ""
libraries[iCalcreator][download][url] = ""
libraries[iCalcreator][directory_name] = "iCalcreator"
libraries[iCalcreator][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.imagesloaded][download][type] = ""
libraries[jquery.imagesloaded][download][url] = ""
libraries[jquery.imagesloaded][directory_name] = "jquery.imagesloaded"
libraries[jquery.imagesloaded][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[phpmailer][download][type] = ""
libraries[phpmailer][download][url] = ""
libraries[phpmailer][directory_name] = "phpmailer"
libraries[phpmailer][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[placeholder][download][type] = ""
libraries[placeholder][download][url] = ""
libraries[placeholder][directory_name] = "placeholder"
libraries[placeholder][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[rijksoverheid-cookie-opt-in][download][type] = ""
libraries[rijksoverheid-cookie-opt-in][download][url] = ""
libraries[rijksoverheid-cookie-opt-in][directory_name] = "rijksoverheid-cookie-opt-in"
libraries[rijksoverheid-cookie-opt-in][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[rs][download][type] = ""
libraries[rs][download][url] = ""
libraries[rs][directory_name] = "rs"
libraries[rs][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[sidr][download][type] = ""
libraries[sidr][download][url] = ""
libraries[sidr][directory_name] = "sidr"
libraries[sidr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish.x][download][type] = ""
libraries[superfish.x][download][url] = ""
libraries[superfish.x][directory_name] = "superfish.x"
libraries[superfish.x][type] = "library"


